### ISSUE TITLE
If syntax

### ISSUE THREAD

**Issue by gurghet** [twitter/effectivescala#72]
I found this snippet in the page

```
val chars = 'a' to 'z'
val perms = chars flatMap { a => 
  chars flatMap { b => 
    if (a != b) Seq("%c%c".format(a, b)) 
    else Seq() 
  }
}
``` 

Could you expand on the legibility of the `if` and `else` as one-liners?

**Comment by mosesn** [comment]
@gurghet I think this is pretty easy to read.  Are you saying that it's not easy to read and we should change it, or you agree it's easy to read and you'd like us to explain why `if (pred) x else y` is easy to read?

**Comment by gurghet** [comment]
I’d like you to explain why. Extra point for [experiments](http://www.cs.loyola.edu/~binkley/papers/icpc09-clouds.pdf).

**Comment by mosesn** [comment]
@gurghet I don't know of any experiments about this, but I think the if/else expressions read pretty naturally in scala.  `if (cond) x else y` is the scala version of the ternary operator `cond ? x : y` which I think is much harder to read, but is also sometimes useful.  When something simple is happening (like in this case), it's nice to not unconditionally add in some of the unnecessary verbosity, like we might in java.

However, I believe the purpose of this example is to explain how you might use flatMap as a filtering tool, by passing back either an empty seq or a seq with items in it.  So I don't think we really want to discuss whether if/else is the right tool here.
